### ISSUE TITLE
Any example of database sync

### ISSUE THREAD

**Issue by sachin0606** [forbesmyester/SyncIt#10]
Hi All, 

any sample example of phonegap/cordova application for tutorial purpose??

thanks

**Comment by forbesmyester** [comment]
Hi,

You should look at http://forbesmyester.github.io/SyncIt/index.html .

**Comment by sachin0606** [comment]
i saw the index file even downloaded the SyncItBootstrap, but unable to find way to start. can you give me sample ionic or cordova app to start?

**Comment by forbesmyester** [comment]
Once checked out you run `./launch_development` or `./launch_production`
from the looks of it... Don't have my main laptop here but if that does not
get you anywhere let me know.

**Comment by forbesmyester** [comment]
Closing as no response.
