### ISSUE TITLE
Implementation in ionic project

### ISSUE THREAD

**Issue by gtzinos** [forbesmyester/SyncIt#9]
Hello,
Is it possible to use your project in a hybrid app based in ionic framework ?

**Comment by forbesmyester** [comment]
Hi,

No reason why not. I put a lot of effort into making it depend on pretty
much nothing so it is super portable.

Thanks

**Comment by gtzinos** [comment]
Okay thank you very much. Please update your README and remove the phrase << What is it for?
SyncIt is a library to enable you to easily add synchronization to your (offline / phonegap or live) web Apps. This may be for allowing multiple users / devices to work offline or because the app has a live editing session with other users. >>. It can be integrated with both ionic and phonegap which are based on cordova project. You can write that is portable with all cordova based frameworks.

**Comment by forbesmyester** [comment]
Thanks, Sure, will do. Re-opening so I don't forget.
